; SPDX-FileCopyrightText: 2026 Peter McGoron
;
; SPDX-License-Identifier: MIT

(define (bytevector-uint-ref bv k e size)
  (unless (and (exact-integer? size)
               (positive? size))
    (error "size: not a positive exact integer" size))
  (if (fixnum? size)
      ((multibyte-ref size #t) bv k e)
      ((multibyte-ref size #f) bv k e)))

(define (bytevector-sint-ref bv k e size)
  (let ((u (bytevector-uint-ref bv k e size))
        (conv (unsigned->signed-factory size)))
    (conv u)))

(define (bytevector-uint-set! bv k n e size)
  (unless (and (exact-integer? size)
               (positive? size))
    (error "size: not a positive exact integer" size))
  (let ((lo 0)
        (hi (- (expt 256 size) 1)))
    (if (fixnum? size)
        ((multibyte-set size lo hi #t) bv k n e)
        ((multibyte-set size lo hi #f) bv k n e)))
  (unless (<= 0 k (+ k size) (bytevector-length bv))
    (error "invalid indicies" k size (bytevector-length bv))))

(define (bytevector-sint-set! bv k n e size)
  (let ((conv (signed->unsigned-factory size)))
    (bytevector-uint-set! bv k (conv n) e size)))

(define-syntax case-rec
  (syntax-rules ()
    ((_ name clauses ...)
     (letrec ((name (case-lambda clauses ...)))
       name))))

(define (to-list accessor)
  (case-rec ->list
    ((bv endianness size)
     (->list bv endianness size 0))
    ((bv endianness size start)
     (->list bv endianness size start
             (bytevector-length bv)))
    ((bv endianness size start end)
     (unless (bytevector? bv)
       (error "not a bytevector" bv))
     (unless (endianness? endianness)
       (error "not an endianness" endianness))
     (unless (and (exact-integer? size) (positive? size))
       (error "not a positive exact integer" size))
     (unless (exact-integer? start)
       (error "not an exact integer" start))
     (unless (exact-integer? end)
       (error "not an exact integer" end))
     (unless (<= 0 start end (bytevector-length bv))
       (error "invalid range" start end))
     (let loop ((i start))
       (if (= i end)
           '()
           (cons (accessor bv i endianness size)
                 (loop (+ i size))))))))

(define bytevector->uint-list (to-list bytevector-uint-ref))
(define bytevector->sint-list (to-list bytevector-sint-ref))

(define (list-bounds? start end list)
  (or (= start end)
      (and (pair? list)
           (list-bounds? (+ start 1) end (cdr list)))))

(define (from-list unsigned? setter!)
  (define (checks! endianness size start)
    (unless (endianness? endianness)
      (error "not an endianness" endianness))
    (unless (and (exact-integer? size) (positive? size))
      (error "not a positive exact integer" size))
    (unless (exact-integer? start)
      (error "not an exact integer" start)))
  (define (make-size-check size)
    (if unsigned?
        (lambda (n)
          (<= 0 n (- (expt 256 size) 1)))
        (lambda (n)
          (<= (- (/ (expt 256 size) 2))
              n
              (- (/ (expt 256 size) 2) 1)))))
  (case-rec list->
    ((list endianness size)
     (list-> list endianness size 0))
    ((list endianness size start)
     (unless (list? list)
       (error "not a list" list))
     (checks! endianness size start)
     (let ((scratch (make-bytevector size))
           (sized? (make-size-check size)))
       (call-with-port (open-output-bytevector)
         (lambda (port)
           (let loop ((list (list-tail list start)))
             (if (null? list)
                 (get-output-bytevector port)
                 (let ((el (car list)))
                   (unless (sized? el)
                     (error "invalid element" el))
                   (begin
                     (setter! scratch 0 el endianness size)
                     (write-bytevector scratch port)
                     (loop (cdr list))))))))))
    ((list endianness size start end)
     (checks! endianness size start)
     (unless (and (<= start end) (list-bounds? start end list))
       (error "invalid bounds" start end))
     (let ((scratch (make-bytevector size))
           (sized? (make-size-check size)))
       (call-with-port (open-output-bytevector)
         (lambda (port)
           (let loop ((list (list-tail list start))
                      (i start))
             (if (= i end)
                 (get-output-bytevector port)
                 (let ((el (car list)))
                   (unless (sized? el)
                     (error "invalid element" el))
                   (begin
                     (setter! scratch 0 el endianness size)
                     (write-bytevector scratch port)
                     (loop (cdr list) (+ i 1))))))))))))

(define uint-list->bytevector (from-list #t bytevector-uint-set!))
(define sint-list->bytevector (from-list #f bytevector-sint-set!))
